### ISSUE TITLE
Exception when opening entity inspector editor for entity with one-to-many relation

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-datatools#7] opened 2020-11-17 11:53 UTC
Project: attached
[zoo.zip](https://github.com/Haulmont/jmix-datatools/files/5553237/zoo.zip)

```
@JmixEntity
@Table(name = "ZOO_ANIMAL_KIND")
@Entity(name = "zoo_AnimalKind")
public class AnimalKind {

...
    @OneToMany(mappedBy = "kind")
    private Set<Animal> animals;
}
```
- launch project
- create one AnimalKind
- create one Animal
- go to Entity Inspector
- select AnimalKind entity
- open the only AnimalKind entity instance for editing

Exception occurs:
![image](https://user-images.githubusercontent.com/6158807/99387090-d5d79380-28ec-11eb-8d1c-cd765aac8942.png)

```
java.lang.IllegalStateException: Cannot get unfetched attribute [kind] from detached object com.company.zoo.entity.Animal-25bb37ac-bc97-ef6a-a4cf-9a35028d3b96 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at io.jmix.data.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027)
	at com.company.zoo.entity.Animal._persistence_checkFetched(Animal.java)
	at com.company.zoo.entity.Animal._persistence_get_kind(Animal.java)
	at com.company.zoo.entity.Animal.getKind(Animal.java:48)
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:73)
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:90)
	at io.jmix.core.entity.EntityValues.getValueEx(EntityValues.java:121)
	at io.jmix.ui.component.data.table.ContainerTableItems.getItemValue(ContainerTableItems.java:116)
	at io.jmix.ui.component.table.TableItemWrapper.getPropertyValue(TableItemWrapper.java:81)
	at io.jmix.ui.component.table.TableItemPropertyWrapper.getValue(TableItemPropertyWrapper.java:37)
	at io.jmix.ui.component.impl.AbstractTable.formatCellValue(AbstractTable.java:1225)
	at io.jmix.ui.widget.JmixTable.formatPropertyValue(JmixTable.java:354)
	at io.jmix.ui.widget.JmixTable.getPropertyValue(JmixTable.java:269)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2371)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2219)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1762)
	at com.vaadin.v7.ui.Table.attach(Table.java:4276)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:571)
	at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:178)
	at com.vaadin.ui.CssLayout.addComponent(CssLayout.java:121)
	at io.jmix.ui.sys.ScreensImpl.showThisTabWindow(ScreensImpl.java:1195)
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:374)
	at io.jmix.ui.screen.Screen.show(Screen.java:306)
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:363)
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:310)
	at io.jmix.ui.component.impl.AbstractTable.handleClickAction(AbstractTable.java:1358)
	at io.jmix.ui.component.impl.AbstractTable.lambda$initComponent$db766529$1(AbstractTable.java:1110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3142)
	at com.vaadin.v7.ui.Table.changeVariables(Table.java:2934)
	at io.jmix.ui.widget.JmixTable.changeVariables(JmixTable.java:366)
```

**Comment by Desire456** [comment] 2021-03-25 13:33
Can't reproduce this problem at Jmix version: 1.0.0-SNAPSHOT

**Comment by owlet1997** [comment] 2021-03-27 13:55
Can't reproduce this problem
Probably was fixed in last versions
Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 0.9.0.SNAPSHOT2685-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**Closed by owlet1997** 2021-03-27 13:55 UTC
Labels: state: won't fix, type: bug
