### ISSUE TITLE
Missed standard filter section in Entity Inspector screen

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-datatools#23] opened 2021-03-02 14:29 UTC
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

run app with dataTool component
Administration>Entity Inspector
ER: filter section shoul be present (like it was in Cuba)
Ar: no filter section
JMIX:

![image](https://user-images.githubusercontent.com/66992566/109663027-177f0800-7b85-11eb-8817-76ff7b4aec07.png)

Cuba:

![image](https://user-images.githubusercontent.com/66992566/109663072-24036080-7b85-11eb-8a27-669d5190e4c1.png)

**Comment by knstvk** [comment] 2021-03-05 07:43
Duplicate of Haulmont/jmix-datatools#26

**Closed by knstvk** 2021-03-05 07:43 UTC
